---
apiVersion: v1
kind: Namespace
metadata:
  name: civicbirth-prod
  labels:
    environment: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: civicbirth-dev
  labels:
    environment: development
